In [1]:
import numpy as np

In [2]:
data = open('puzzle.txt','r')

data.seek(0)

0

In [3]:
data.seek(0)
arrayList = []
for i in data.readlines():
    i = i.strip('\n')
    if(i != '\n'):
        i = i.split(' ')
        arrayList.append(i)

for i in range(len(arrayList)):
    if arrayList[i] == '':
        arrayList.remove(i)
    for j in arrayList[i]:
        if j == '':
            arrayList[i].remove(j)
arrayList = [x for x in arrayList if x]


In [4]:
A = np.array(arrayList,dtype=np.int64).reshape(2500,)
A = A.reshape(100,5,5)
A


array([[[14, 86, 50, 89, 49],
        [10, 85, 33, 46, 87],
        [82, 91, 54, 13, 90],
        [63, 88, 75, 99, 79],
        [74, 31,  4,  0, 71]],

       [[56,  3, 70,  2, 22],
        [44, 63, 10, 95,  8],
        [92, 62, 83,  4, 93],
        [74, 80,  5, 11, 68],
        [24, 50, 42, 65, 72]],

       [[42, 21, 72, 26,  7],
        [ 4, 78,  1, 49, 50],
        [93, 43, 38, 71, 68],
        [62, 52, 40, 61, 82],
        [31, 28, 16, 96, 18]],

       ...,

       [[73, 37, 66, 67, 19],
        [16, 79, 15, 45, 89],
        [84, 78, 69, 28, 46],
        [17,  4, 12, 95, 87],
        [49, 99, 31,  9, 36]],

       [[61, 34, 98, 60, 74],
        [30, 95, 33, 46, 64],
        [73, 97, 12, 26,  7],
        [ 2, 58, 49, 70, 54],
        [80, 55, 94, 91, 11]],

       [[27,  5,  3, 62, 49],
        [38, 88, 40,  9, 47],
        [29, 59, 94, 74, 12],
        [48, 73, 85, 97, 35],
        [28, 25, 30, 14, 83]]])

In [5]:

with open('puzzle_1.txt', 'r') as inp:
    b = np.array(inp.read().strip('\n').split(','),dtype=np.int64)
b



array([13, 79, 74, 35, 76, 12, 43, 71, 87, 72, 23, 91, 31, 67, 58, 61, 96,
       16, 81, 92, 41,  6, 32, 86, 77, 42,  0, 55, 68, 14, 53, 26, 25, 11,
       45, 94, 75,  1, 93, 83, 52,  7,  4, 22, 34, 64, 69, 88, 65, 66, 39,
       97, 27, 29, 78,  5, 49, 82, 54, 46, 51, 28, 98, 36, 48, 15,  2, 50,
       38, 24, 89, 59,  8,  3, 18, 47, 10, 90, 21, 80, 73, 33, 85, 62, 19,
       37, 57, 95, 60, 20, 99, 17, 63, 56, 84, 44, 40, 70,  9, 30])

In [9]:
index = 0
marked = list()
for bindex in b[index:index+5]:
    for i in range(0,len(A)):
        for j in range(0, len(A[0])):
            for i in range(len(marked)):
                marked.pop(i)
            for k in A[j,]:
                if bindex == k.any():
                    marked.append(k)
                    if len(marked) == 5:
                        print((np.sum(A[i]) - np.sum(A[j,]))*marked[-1])
                


In [27]:
marked = list()
for index in b:
    for i in range(0,len(A)):
        M = np.array(A[i])
        row = 0
        for j in range(len(A[i,])):
            print((np.sum(M[i]) - np.sum(M[j,]))*index)
            for k in M[j,]:
                if index == k:
                    row += 1
                    if row == 5:
                        print((np.sum(M[i]) - np.sum(M[j,]))*index)
            
                
    
    
            


0
351
-546
-1508
1404
871
0
-1482
-234
-429
1885
1703
0
208
1612
-1222
-169
-104
0
-624
-2418
-2015
-598
-1612
0


IndexError: index 5 is out of bounds for axis 0 with size 5

In [11]:
M = np.array([[27,  5,  3, 62, 49],
        [38, 88, 40,  9, 47],
        [29, 59, 94, 74, 12],
        [48, 73, 85, 97, 35],
        [28, 25, 30, 14, 83]])

In [12]:
np.where(M[0,] == 5)

(array([1]),)

In [20]:
np.sum(M)

1154

In [14]:
M.T

array([[27, 38, 29, 48, 28],
       [ 5, 88, 59, 73, 25],
       [ 3, 40, 94, 85, 30],
       [62,  9, 74, 97, 14],
       [49, 47, 12, 35, 83]])

In [18]:
np.linalg.inv(M).dot(np.identity(5))

array([[-0.21250123, -0.11070012, -0.29975668,  0.36349084,  0.07819719],
       [ 0.07454958,  0.05333029,  0.09527693, -0.11988122, -0.03743294],
       [-0.03767819, -0.02232061, -0.02054297,  0.03871908,  0.02152588],
       [ 0.06323849,  0.02514405,  0.07008518, -0.08199581, -0.02712801],
       [ 0.05218436,  0.0251078 ,  0.06802844, -0.08667884, -0.00626123]])

In [19]:
np.trace(M)

389